#!/usr/bin/env bash
# buzz-tui installer — builds the daemon, installs JS deps, symlinks launcher.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/another-level-of-indirection/buzz-tui/hybrid-monorepo/install.sh | bash
# Or locally:
#   ./install.sh
set -euo pipefail

REPO_DIR="${BUZZ_TUI_DIR:-$HOME/.local/share/buzz-tui}"
BIN_DIR="${BUZZ_TUI_BIN:-$HOME/.local/bin}"

echo "buzz-tui installer"
echo "==================="

# Check prerequisites
for cmd in cargo bun git; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "error: $cmd is required but not installed" >&2
    exit 1
  fi
done

RUST_VERSION=$(rustc --version | awk '{print $2}')
echo "  rust:  $RUST_VERSION"
echo "  bun:   $(bun --version)"
echo "  dest:  $REPO_DIR"
echo "  bin:   $BIN_DIR"
echo ""

# Clone or update
if [ -d "$REPO_DIR/.git" ]; then
  echo "Updating existing installation…"
  cd "$REPO_DIR"
  git pull --ff-only
else
  echo "Cloning repository…"
  git clone --branch hybrid-monorepo https://github.com/another-level-of-indirection/buzz-tui.git "$REPO_DIR"
  cd "$REPO_DIR"
fi

# Build Rust daemon
echo ""
echo "Building buzz-sessiond…"
cargo build -p buzz-sessiond --release --quiet

# Install JS dependencies
echo "Installing TypeScript dependencies…"
bun install --cwd "$REPO_DIR"

# Create launcher script
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/buzz-tui" <<LAUNCHER
#!/usr/bin/env bash
# buzz-tui launcher — auto-generated by install.sh
set -euo pipefail
export BUZZ_SESSIOND_PATH="$REPO_DIR/target/release/buzz-sessiond"
exec bun run "$REPO_DIR/packages/shell/index.ts" "\$@"
LAUNCHER
chmod +x "$BIN_DIR/buzz-tui"

echo ""
echo "Installed! Make sure $BIN_DIR is in your PATH, then run:"
echo ""
echo "  export BUZZ_RELAY_URL=https://your.relay"
echo "  export BUZZ_PRIVATE_KEY=your-key"
echo "  buzz-tui"
echo ""

# Version handshake check
DAEMON_VERSION=$("$REPO_DIR/target/release/buzz-sessiond" --version 2>/dev/null || echo "unknown")
echo "  daemon: $DAEMON_VERSION"
echo "  shell:  hybrid-monorepo"
echo ""
echo "Done."
